version: '3.8'

services:
  groover_db:
    image: postgres
    env_file:
      - postgres.env

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A groover_challenge worker -l INFO
    volumes:
      - .:/groover_challenge
    env_file:
      - app.env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A groover_challenge beat -l INFO
    volumes:
      - .:/groover_challenge
    env_file:
      - app.env
    depends_on:
      - redis

  groover_api:
    build: .
    entrypoint: /entrypoint.sh
    command: python manage.py runserver 0.0.0.0:5000
    container_name: groover_challenge
    volumes:
      - .:/groover_challenge
    env_file:
      - app.env
    ports:
      - "5000:5000"
    depends_on:
      - celery
      - groover_db
